[package]
name = "kuro-run"
version = "0.1.0"
edition = "2024"
authors = ["Amartya Chowdhury work.amar05@yahoo.com"]
description = "An experimental OCI container runtime built in Rust."
readme = "README.md"
repository = "https://github.com/aether-flux/kuro"
license = "MIT"
keywords = ["container", "oci", "runtime", "namespaces", "linux"]
categories = ["command-line-utilities", "os::linux-apis"]

[dependencies]
caps = { version = "0.5.6", features = ["serde", "serde_support"] }
clap = { version = "4.6.6", features = ["derive"] }
libc = "0.2.189"
nix = { version = "0.31.3", features = [
  "process",
  "mount",
  "sched",
  "signal",
  "user",
  "fs",
  "hostname",
  "resource",
  "term",
  "socket",
] }
oci-spec = "0.10.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
syscallz = "0.17.0"
thiserror = "2.0.20"
